
# Read in the data

# Note: Change Filename once the data is finalized
FileName <- "/Users/huangzm/Desktop/ML 1/HW2/SelfieImageData-Final.csv"
Labs <- scan(file=FileName,what="xx",nlines=1,sep="|")
DataAsChars <- matrix(scan(file=FileName,what="xx",sep="|",skip=1),byrow=T,ncol=length(Labs))
colnames(DataAsChars) <- Labs
dim(DataAsChars)
# size in memory in MBs
as.double(object.size(DataAsChars)/1024/1024)

ImgData <- matrix(as.integer(DataAsChars[,-1]),nrow=nrow(DataAsChars))
colnames(ImgData) <- Labs[-1]
rownames(ImgData) <- DataAsChars[,1]
# size in memory in MBs
as.double(object.size(ImgData)/1024/1024)

# Take a look
ImgData[1:8,1:8]
dim(ImgData)

# Free up some memory just in case
remove(DataAsChars)

# Show each Image
for(whImg in 1:nrow(ImgData)) {
  Img <- matrix(ImgData[whImg,],byrow=T,ncol=sqrt(ncol(ImgData)))
  Img <- apply(Img,2,rev)
  par(pty="s",mfrow=c(1,1))
  image(z=t(Img),col = grey.colors(255),useRaster=T)
  Sys.sleep(1)
}

# -------------------------------------------------------------------------
# Q2. AVREAGE FACE
Xmean = apply(ImgData,2,FUN=mean)
length(Xmean)
mean_Img <- matrix(Xmean,byrow=T,ncol=sqrt(length(Xmean)))
mean_Img <- apply(mean_Img,2,rev)
dim(mean_Img)
par(pty="s",mfrow=c(1,1))
image(z=t(mean_Img),col = grey.colors(255),useRaster=T)

# -------------------------------------------------------------------------
Xc = sweep(ImgData,2,Xmean,'-')
sum(ImgData[,1] - Xmean[1] != Xc[,1])

mean(Xc[,1])
mean(Xc[,226])
mean(Xc[,10000]) # check if the mean of each col is 0
Xc[,226*226] # check the eye

# Compute the small matrix
small_matrix = Xc%*%t(Xc)
dim(small_matrix)

# Compute Eigenvalues and Eigenvectors for small_matrix
SDecomp = eigen(small_matrix) 
Sig2 = SDecomp$vectors%*%diag(SDecomp$values)%*%t(SDecomp$vectors)
range(abs(Sigma-Sig2)) 

# make sure orthogonal & normal
tmp1 = t(SDecomp$vectors)%*%SDecomp$vectors
range(abs(tmp1-diag(nrow(tmp1)))) 


# Compute Eigenvalues and Eigenvectors for full matrix
eigen_values = SDecomp$values/(length(SDecomp$values)-1)
XcV = t(Xc)%*%SDecomp$vectors
dim(XcV)
eigen_vectors = sweep(XcV, 2, sqrt(colSums(XcV^2)), FUN = "/")
dim(eigen_vectors)

tmp1 = t(eigen_vectors)%*%eigen_vectors
range(abs(tmp1-diag(nrow(tmp1)))) 
# the maximum is 0.5, so I further randomly check some eigenvectors

# random check normal
vector_of_zero = numeric(nrow(eigen_vectors))
dist_matrix = rbind(vector_of_zero, eigen_vectors[,1])
dim(dist_matrix)                   
dist(dist_matrix)
dist(rbind(vector_of_zero, eigen_vectors[,11]))
dist(rbind(vector_of_zero, eigen_vectors[,21]))
dist(rbind(vector_of_zero, eigen_vectors[,31]))

# random check orthogonal
t(eigen_vectors[,1,drop=F])%*%eigen_vectors[,11,drop=F]
t(eigen_vectors[,23,drop=F])%*%eigen_vectors[,31,drop=F]
t(eigen_vectors[,15,drop=F])%*%eigen_vectors[,25,drop=F]

# -------------------------------------------------------------------------
# Q5 SCREE PLOT
plot(cumsum(eigen_values)/sum(eigen_values), 
     main = "Scree Plot PCA", xlab = "Number of Eigenvalues",
     ylab = "Cumulative Porportion of Variance Explained")
ytick = seq(0.4, 1, by=0.05)
axis(side=2, at=ytick, labels = FALSE)

# -------------------------------------------------------------------------
# Q6 largest eigenvalue
options(scipen = 999) # turn off scientific notation
largest = round(eigen_values[1],digit = 2)
largest
options(scipen = 0) # turn on scientific notation

# -------------------------------------------------------------------------
# Q7 85% variance
sum(cumsum(eigen_values)/sum(eigen_values) < 0.85) + 1
sum(eigen_values[1:25])/sum(eigen_values)

# -------------------------------------------------------------------------
# Q8 20 dimension
d = 20
sum(eigen_values[1:d])/sum(eigen_values)

# reconstruct data using PC
PComp_Selfie = ImgData%*%eigen_vectors[,1:d]
colnames(PComp_Selfie) = paste("PC",1:d)
dim(PComp_Selfie)
Recon_Selfie = PComp_Selfie%*%t(eigen_vectors[,1:d])
rownames(Recon_Selfie) = rownames(ImgData)
rownames(Recon_Selfie)

# reconstructed selfie
Self_Img = matrix(Recon_Selfie["Ziming Huang ",],byrow=T,ncol=sqrt(ncol(Recon_Selfie)))
Self_Img = apply(Self_Img,2,rev)
par(pty="s",mfrow=c(1,1))
image(z=t(Self_Img),col = grey.colors(255),useRaster=T)

# original selfie
for(whImg in 50:50) {
  Img <- matrix(ImgData[whImg,],byrow=T,ncol=sqrt(ncol(ImgData)))
  Img <- apply(Img,2,rev)
  par(pty="s",mfrow=c(1,1))
  image(z=t(Img),col = grey.colors(255),useRaster=T)
  Sys.sleep(1)
}


# -------------------------------------------------------------------------
# Q10 eigenface

# check the picture generated by the nth eigen-vector
check_eigen_image = function(k){
  vec = eigen_vectors[,k]
  vec = (vec-min(vec))/(max(vec)-min(vec))
  vec = vec*255
  range(vec)
  vecImage = matrix(vec,byrow=T,ncol=sqrt(ncol(ImgData)))
  vecImage = t(apply(vecImage,2,rev))
  image(z=vecImage,col = grey.colors(255),useRaster=T)
}

for(whImg in 1:20) {
  vec = eigen_vectors[,whImg]
  vec = (vec-min(vec))/(max(vec)-min(vec))
  vec = vec*255
  range(vec)
  vecImage = matrix(vec,byrow=T,ncol=sqrt(ncol(ImgData)))
  vecImage = t(apply(vecImage,2,rev))
  image(z=vecImage,col = grey.colors(255),useRaster=T)
  Sys.sleep(1)
}

check_eigen_image(8)
check_eigen_image(12)
check_eigen_image(10)
check_eigen_image(13)



